-- Utilisation de la base de données
USE _________________;

-- Table : COMMENTAIRE
CREATE TABLE COMMENTAIRE
(
    COM_ID INT NOT NULL,
    COM_CONTENU VARCHAR(255) NOT NULL,
    COM_USER INT NOT NULL,
    PRIMARY KEY (COM_ID)
);

-- Table : RECETTE
CREATE TABLE RECETTE
(
    RC_ID INT NOT NULL,
    RC_TITRE VARCHAR(100) NOT NULL,
    RC_CONTENU VARCHAR(100) NOT NULL,
    RC_RESUME VARCHAR(100) NOT NULL,
    RC_CATEGORIE INT NOT NULL,
    RC_RECETTE_DATE_INSCRIPTION DATE NOT NULL,
    RC_IMAGE VARCHAR(100) NOT NULL,
    RC_RECETTE_DATE_CREATION DATE NOT NULL,
    RC_RECETTE_DATE_MODIFICATION DATE NOT NULL,
    RC_AUTEUR INT NOT NULL,
    PRIMARY KEY (RC_ID)
);

-- Table : UTILISATEUR
CREATE TABLE UTILISATEUR
(
    USR_ID INT NOT NULL,
    USR_PSEUDO VARCHAR(32) NOT NULL,
    USR_EMAIL VARCHAR(32),
    USR_PRENOM VARCHAR(32) NOT NULL,
    USR_NOM VARCHAR(32),
    USR_DATE_INSCRIPTION DATE NOT NULL,
    USR_TYPE INT NOT NULL,
    USR_STATUT INT NOT NULL,
    USR_PASSWORD VARCHAR(32) NOT NULL,
    PRIMARY KEY (USR_ID)
);

-- Table : CATEGORIE
CREATE TABLE CATEGORIE
(
    CAT_ID INT NOT NULL,
    CAT_INTITULE VARCHAR(255) NOT NULL,
    CAT_DESC VARCHAR(255) NOT NULL,
    PRIMARY KEY (CAT_ID)
);

-- Table : INGREDIENT
CREATE TABLE INGREDIENT
(
    INGR_ID INT NOT NULL,
    INGR_INTITULE VARCHAR(100) NOT NULL,
    INGR_DESC VARCHAR(100) NOT NULL,
    PRIMARY KEY (INGR_ID)
);

-- Table : RECETTE_INGREDIENT
CREATE TABLE RECETTE_INGREDIENT
(
    RI_ID INT NOT NULL,
    RI_RECETTE INT NOT NULL,
    RI_INGREDIENT INT NOT NULL,
    RI_QUANTITE INT NOT NULL,
    PRIMARY KEY (RI_ID)
);

-- Ajoutez les contraintes de clé étrangère à la fin de la création des tables

-- Contrainte de clé étrangère pour la table COMMENTAIRE
ALTER TABLE COMMENTAIRE
ADD CONSTRAINT FK_COMMENTAIRE_UTILISATEUR
FOREIGN KEY (COM_USER) REFERENCES UTILISATEUR (USR_ID);

ALTER TABLE COMMENTAIRE
ADD CONSTRAINT FK_COMMENTAIRE_RECETTE
FOREIGN KEY (COM_ID) REFERENCES RECETTE (RC_ID);

-- Contrainte de clé étrangère pour la table RECETTE
ALTER TABLE RECETTE
ADD CONSTRAINT FK_RC_CATEGORIE
FOREIGN KEY (RC_CATEGORIE) REFERENCES CATEGORIE (CAT_ID);

ALTER TABLE RECETTE
ADD CONSTRAINT FK_RC_AUTEUR
FOREIGN KEY (RC_AUTEUR) REFERENCES UTILISATEUR (USR_ID);

-- Contrainte de clé étrangère pour la table RECETTE_INGREDIENT
ALTER TABLE RECETTE_INGREDIENT
ADD CONSTRAINT FK_RI_RECETTE
FOREIGN KEY (RI_RECETTE) REFERENCES RECETTE (RC_ID);

ALTER TABLE RECETTE_INGREDIENT
ADD CONSTRAINT FK_RI_INGREDIENT
FOREIGN KEY (RI_INGREDIENT) REFERENCES INGREDIENT (INGR_ID);


-- FIN DE LA CRÉATION